INPUT_TEXT = "AATGCGTCCGCAGGAAAGGCTGGCAATCGTTATTCGCAGGAAAAATGCGTCATCGTTATTATCGTTATTACTCGACTGGCTGGCAGGCTGGCAATCGTTATTATCGTTATTACTCGACTAATGCGTCGGCTGGCAATCGTTATTACTCGACTAATGCGTCCGCAGGAAAACTCGACTAATGCGTCCGCAGGAAAACTCGACTACTCGACTATCGTTATTGGCTGGCAAATGCGTCGGCTGGCAGGCTGGCAAATGCGTCGGCTGGCAGGCTGGCAATCGTTATTAATGCGTCGGCTGGCACGCAGGAAAAATGCGTCAATGCGTCGGCTGGCACGCAGGAAACGCAGGAAAATCGTTATTATCGTTATTACTCGACTACTCGACTAATGCGTCATCGTTATTACTCGACTATCGTTATTATCGTTATTGGCTGGCACGCAGGAAAACTCGACTCGCAGGAAAGGCTGGCACGCAGGAAAATCGTTATTAATGCGTCATCGTTATTAATGCGTCAATGCGTCACTCGACTATCGTTATTGGCTGGCAATCGTTATTCGCAGGAAAGGCTGGCAAATGCGTCACTCGACTACTCGACTATCGTTATTCGCAGGAAAACTCGACTACTCGACTCGCAGGAAAACTCGACTACTCGACTCGCAGGAAAAATGCGTCCGCAGGAAACGCAGGAAACGCAGGAAAGGCTGGCACGCAGGAAAACTCGACTATCGTTATTGGCTGGCAACTCGACTACTCGACTAATGCGTCACTCGACTAATGCGTCAATGCGTCAATGCGTCACTCGACTATCGTTATTGGCTGGCAACTCGACT"

def pattern_count(text, pattern):
    count = 0
    len_pattern = len(pattern)
    for i in range(0, len(text)-len_pattern+1):
        if text[i:i+len_pattern] == pattern:
            count += 1
    return count

def frequent_words(text, k):
    freq = []
    count = []
    for i in range(0, len(text)-k+1):
        pattern = text[i:i+k]
        pat_count = pattern_count(text, pattern)
        count.append(pat_count)
    max_count = sorted(count, reverse=True)[0]
    for i in range(0, len(text)-k+1):
        if count[i] == max_count:
            if not text[i:i+k] in freq:
                freq.append(text[i:i+k])
    return freq

if __name__ == "__main__":
    freq = frequent_words(INPUT_TEXT, 13)
    for word in freq:
        print word
